### ISSUE TITLE
Unable to train

### ISSUE THREAD

**Issue by foragony** [HeegerGao/DMIL#1]
Is there something wrong with the production of training data? It seems that the size of each trajectory in the data is not the same, so in training, the iterative data cannot be stack properly. The following is the error:
Traceback (most recent call last):
  File "/root/Desktop/code/OSIL/temp/DMIL/metaworld/maml.py", line 212, in <module>
    maml_train(args, high_level_net, sub_skills, high_model_name, sub_skill_name)
  File "/root/Desktop/code/OSIL/temp/DMIL/metaworld/maml.py", line 20, in maml_train
    spt_state, spt_action = next(iter(dmil_loaders[task_name]))  # shape: [batch_size, length, size]
  File "/root/miniconda3/envs/robot/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/robot/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/envs/robot/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/root/miniconda3/envs/robot/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/root/miniconda3/envs/robot/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/root/miniconda3/envs/robot/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/root/miniconda3/envs/robot/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [97, 39] at entry 0 and [101, 39] at entry 1

**Comment by F-GOD6** [comment]
I have the question too,have you solve it?
